version: 0.2

phases:

  install:
    commands:
      - echo "Starting build environment..."

  pre_build:
    commands:
      - echo "Starting website validation..."

  build:
    commands:
      - echo "Checking frontend files..."
      - test -f Frontend/index.html
      - test -f Frontend/style.css
      - test -f Frontend/script.js
      - echo "All frontend files are present."

  post_build:
    commands:
      - echo "Validation successful. Deploing website to S3..."
      - 'aws s3 sync Frontend/ s3://secure-static-website-b1/Frontend/'
      - echo "Website deployed successfully to S3 bucket."
      - 'aws cloudfront create-invalidation --distribution-id E60LMWR8OLTZ2 --paths "/*"'
      - echo "CloudFront cache invalidation request sent."