version: 0.2

phases:

  install:
    commands:
      - echo "Starting build environment..."

  pre_build:
    commands:
      - echo "Starting website validation..."

  build:
    commands:
      - echo "Checking frontend files..."
      - test -f Frontend/index.html
      - test -f Frontend/style.css
      - test -f Frontend/script.js
      - echo "All frontend files are present."

  post_build:
    commands:
      - echo "Validation successful.Proceeding to deployment..."
  
artifacts:
  base-directory: Frontend
  files:
    - '**/*'
